Linux: Added stubs for bluetooth. Fixed a couple more compile errors. Currently linking test_psmove_controller failes because libPSMoveClient_CAPI.so has undefined reference to shm_open.